version: "3.2"

services:
  residents-social-care-platform-api:
    image: residents-social-care-platform-api
    build:
      context: ResidentsSocialCarePlatformApi/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - CONNECTION_STRING=Host=dev-database;Port=5432;Database=testsocialcare;Username=postgres;Password=mypassword
    links:
      - dev-database
  dev-database:
    env_file:
      - database.env
    image: postgres:12

  residents-social-care-platform-api-test:
    image: residents-social-care-platform-api-test
    build:
      context: .
      dockerfile: ResidentsSocialCarePlatformApi.Tests/Dockerfile
    environment:
      - DB_HOST=test-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_DATABASE=testsocialcare
    links:
      - test-database
  test-database:
    image: test-database
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - 5432:5432
    env_file:
      - database.env
